title: <h1>b</h1><s>a</s>
description: <h1>a</h1><s>a</s>
template:
  repo: lessh1greaterblessh1greaterlesssgreateralesssgreater-template
  name: lessh1greaterblessh1greaterlesssgreateralesssgreater
before:
  - type: createIssue
    title: Welcome!
    body: new-issue.md
steps:
  - title: <h1>a</h1><s>a</s>
    description: <h1>a</h1><s>a</s>
    event: issues.assigned
    link: '{{ repoUrl }}'
    actions:
      - type: closeIssue
  - title: New step
    actions:
      - type: createIssue
        title: A new issue
        body: a-response-file.md
